spring:
  activemq:
    #配置指定服务端ip和端口
    broker-url: failover:(tcp://${brokerIp}:61616,tcp://${brokerIp}:61617,tcp://${brokerIp}:61618)
    #配置登录用户名
    user: admin
    #配置登录密码
    password: admin
    pool:
      #最大连接数
      max-connections: 100
  jms:
    pub-sub-domain: false

server:
  port: 8081

brokerIp: 111.230.202.74